<?php /* @var $block \Magento\Catalog\Block\Product\View\Description */  ?>

<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View\Description
 */
?>

<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();

$renderLabel = true;
// if defined as 'none' in layout, do not render
if ($_attributeLabel == 'none') {
    $renderLabel = false;
}



// Simple product could have a Configurable parent
// Usually we use the same Short_description/Description for simples and conf but check the flag
// Will take description or short_description value from the first enabled configurable parent
// if the custom 'fdscc_description'/'fdscc_shortdescription' attribute is 'Yes'
$blockObj= $block->getLayout()->createBlock('Fds\Customcatalog\Block\Product\Customcatalog');
$tempAttributeValue = $blockObj->getConfigurableAttribute($_product, $_code, $_helper, $_call);
if ($tempAttributeValue != ''){
    $_attributeValue = $tempAttributeValue;
}
$from_config = ($tempAttributeValue != '');



if (!($from_config)){
    if ($_attributeLabel && $_attributeLabel == 'default') {
        $_attributeLabel = $_product->getResource()->getAttribute($_code)->getStoreLabel();
    }
    if ($_attributeType && $_attributeType == 'text') {
        $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : '';
    } else {
        $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
    }
}

?>

<?php if ($_attributeValue): ?>
    <div class="product attribute <?= /* @escapeNotVerified */ $_className ?>">
        <?php if ($renderLabel): ?><strong class="type"><?= /* @escapeNotVerified */ $_attributeLabel ?></strong><?php endif; ?>
        <div class="value" <?= /* @escapeNotVerified */ $_attributeAddAttribute ?>><?= /* @escapeNotVerified */ $_attributeValue ?></div>
    </div>
<?php endif; ?>
