<?php /* @var $block \Fds\Superbundle\Block\Product\SuperbundleProduct */  ?>

<?php

/**
 * Fds_Superbundle
 * Fds - fdallserra 2018
 * Product page bundle:
 *     if box bundle
 *     no reviews
 */

    $isBoxBundle = false;
    $bundle = $block->getProduct();
    $blockObj= $block->getLayout()->createBlock('Fds\Superbundle\Block\Cart\SuperbundleCartItem');
    $isBoxBundle =  $blockObj->isBoxBundle($bundle).'';

?>

<?php if ($isBoxBundle):

    $layout = $this->getLayout();
    $layout->unsetElement('reviews.tab');
    $layout->unsetElement('product.review.form');

 ?>

<?php else : ?>

    <?php
    $blockObj= $block->getLayout()->createBlock('\Magento\Catalog\Block\Product\AbstractProduct'); ?>
    <?= $blockObj->getReviewsSummaryHtml($block->getProduct(), false, true) ?>

<?php endif; ?>
