<?php /* @var $block \Fds\Superbundle\Block\Product\SuperbundleProduct */  ?>

<?php

/**
 * Fds_Superbundle
 * Fds - fdallserra 2018
 * Product page bundle:
 *     NOT IMPLEMENTED
 *     if box bundle
 *     Description from Single Product
 */

$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();


//***
$isBoxBundle = false;
$description = '';

$blockObj = $block->getLayout()->createBlock('Fds\Superbundle\Block\Cart\SuperbundleCartItem');
$isBoxBundle = $blockObj->isBoxBundle($_product) . '';

if ($isBoxBundle) {
    $dataBox = $block->getDataBox($_product);
    $description = $dataBox['description'];
}
//***

$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();

$renderLabel = true;
// if defined as 'none' in layout, do not render
if ($_attributeLabel == 'none') {
    $renderLabel = false;
}

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getStoreLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>
<?php if ($_attributeValue): ?>
    <div class="product attribute <?= /* @escapeNotVerified */ $_className ?>">
        <?php if ($renderLabel): ?><strong class="type"><?= /* @escapeNotVerified */ $_attributeLabel ?></strong><?php endif; ?>
        <div class="value" <?= /* @escapeNotVerified */ $_attributeAddAttribute ?>><?= /* @escapeNotVerified */ $_attributeValue ?></div>
    </div>
<?php endif; ?>
