<?php /* @var $block \Fds\Superbundle\Block\Cart\SuperbundleCart */  ?>

<?php

/**
 * Fds_Superbundle
 * Fds - fdallserra 2018
 * Cart:
 *     if bundle box
 *     change url to single product in link and image
 *     description and regular price plus discounted price
 */

    $_item = $block->getItem();
    $product = $_item->getProduct();
    $isVisibleProduct = $product->isVisibleInSiteVisibility();

    $helper = $this->helper('Magento\Msrp\Helper\Data');
    $canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);

    $isBoxBundle = false;
    $hasProductUrl = false;
    $url_single_product = '';

    //is the product boxbundle?
    $blockObj= $block->getLayout()->createBlock('Fds\Superbundle\Block\Cart\SuperbundleCartItem');
    $url_single_product =  $blockObj->getUrlSingleProduct($product);
    if ($url_single_product == ''){
        $url_single_product = $block->getProductUrl();
    } else {
        $isBoxBundle = true;
        $blockProgObj = $block->getLayout()->createBlock('Fds\Superbundle\Block\Product\SuperbundleProduct');
        $dataBox = $blockProgObj->getDataBox($product);

        $superBundle = $blockObj->getSingleProduct($product);
        $description = $dataBox['qty'] . ' x ' . $superBundle->getName();
    }

    $hasProductUrl = ($url_single_product <> '');

?>
<tbody class="cart item">
<tr class="item-info">
    <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item">
        <?php if ( $hasProductUrl):?>
        <a href="<?= /* @escapeNotVerified */ $url_single_product ?>"
           title="<?= $block->escapeHtml($block->getProductName()) ?>"
           tabindex="-1"
           class="product-item-photo">

            <?php else:?>
            <span class="product-item-photo">
            <?php endif;?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($hasProductUrl):?>
        </a>

    <?php else: ?>
        </span>
    <?php endif; ?>
        <div class="product-item-details">
            <strong class="product-item-name">
                <?php if ( $hasProductUrl):?>
                    <a href="<?= /* @escapeNotVerified */ $url_single_product ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>

                <?php else: ?>
                    <?= $block->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>
            <?php if ($_options = $block->getOptionList()):?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dt><?= $block->escapeHtml($_option['label']) ?></dt>

                        <?php if ($isBoxBundle):?>
                            <dd>
                                <?= /* @escapeNotVerified */ $description ?>

                                <br>
                                <?php if ($dataBox['reg_price'] <> $dataBox['price']):?>
                                    <span class="cartPrice"><?php echo (__('As low as')) ?>&nbsp;<?php echo $dataBox['price']; ?></span>&nbsp;
                                    <span class="cartOldPrice"><?php echo (__('Regular price')) ?>&nbsp;<?php echo $dataBox['reg_price']; ?></span>
                                <?php else: ?>
                                    <span class="cartPrice"><?php echo (__('Price')) ?>&nbsp;<?php echo $dataBox['price']; ?></span>
                                <?php endif; ?>

                            </dd>

                        <?php else: ?>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                    <?= /* @escapeNotVerified */ $_formatedOptionValue['full_view'] ?>
                                <?php else: ?>
                                    <?= /* @escapeNotVerified */ $_formatedOptionValue['value'] ?>
                                <?php endif; ?>
                            </dd>
                        <?php endif;?>


                    <?php endforeach; ?>
                </dl>
            <?php endif;?>
            <?php if ($messages = $block->getMessages()): ?>
                <?php foreach ($messages as $message): ?>
                    <div class="cart item message <?= /* @escapeNotVerified */ $message['type'] ?>"><div><?= $block->escapeHtml($message['text']) ?></div></div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock): ?>
                <?= $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif;?>
        </div>
    </td>

    <?php if ($canApplyMsrp): ?>
        <td class="col msrp" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= /* @escapeNotVerified */ __('See price before order confirmation.') ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map" id="<?= /* @escapeNotVerified */ ($helpLinkId) ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?= /* @escapeNotVerified */ $helpLinkId ?>","productName": "<?= /* @escapeNotVerified */ $product->getName() ?>","showAddToCart": false}}'>
                        <span><?= /* @escapeNotVerified */ __("What's this?") ?></span>
                    </a>
                </span>
        </td>
    <?php else: ?>
        <td class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
            <?= $block->getUnitPriceHtml($_item) ?>
        </td>
    <?php endif; ?>
    <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
        <div class="field qty">
            <label class="label" for="cart-<?= /* @escapeNotVerified */ $_item->getId() ?>-qty">
                <span><?= /* @escapeNotVerified */ __('Qty') ?></span>
            </label>
            <div class="control qty">
                <input id="cart-<?= /* @escapeNotVerified */ $_item->getId() ?>-qty"
                       name="cart[<?= /* @escapeNotVerified */ $_item->getId() ?>][qty]"
                       data-cart-item-id="<?= $block->escapeHtml($_item->getSku()) ?>"
                       value="<?= /* @escapeNotVerified */ $block->getQty() ?>"
                       type="number"
                       size="4"
                       title="<?= $block->escapeHtml(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="{required:true,'validate-greater-than-zero':true}"
                       data-role="cart-item-qty"/>
            </div>
        </div>
    </td>

    <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
        <?php if ($canApplyMsrp): ?>
            <span class="cart msrp subtotal">--</span>
        <?php else: ?>
            <?= $block->getRowTotalHtml($_item) ?>
        <?php endif; ?>
    </td>
</tr>
<tr class="item-actions">
    <td colspan="100">
        <div class="actions-toolbar">
            <?= /* @escapeNotVerified */ $block->getActions($_item) ?>
        </div>
    </td>
</tr>
</tbody>

